### ISSUE TITLE
Add to support to rotate the private key for your public certificate automatically

### ISSUE THREAD

**Issue by SIDDHARTHA-PRADHAN1** [terraform-ibm-modules/terraform-ibm-secrets-manager-public-cert#36]
### Description

Add variable to support to rotate the private key for your public certificate automatically by adding [rotate_keys](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/sm_public_certificate#rotate_keys) to true.

By default the `Rekey during rotation` is false.But need the ability to make use of it while creating public certs.
![image](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-public-cert/assets/170326798/708c8017-efef-4583-b9fb-f46651c52eca)

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by alex-reiff** [comment]
PR merged, closing.

**Comment by alex-reiff** [comment]
@SIDDHARTHA-PRADHAN1 This is included in v1.1.0
